Middleware support
zensum/franz pull request #18
Opened 2018-05-28 07:59 UTC by bonahona

Added possibility to install interceptors into the workflow.

2018-05-28 08:35 UTC, williamhogman approved these changes
Only minor things

2018-05-28 08:35 UTC, williamhogman commented on src/main/kotlin/WorkerBuilder.kt
> +import com.sun.xml.internal.ws.api.pipe.FiberContextSwitchInterceptor
Remove plz

2018-05-28 08:35 UTC, williamhogman commented on src/main/kotlin/JobState.kt
> +        val lastInterceptor = WorkerInterceptor {
Could we avoid this allocation in some easy way? If no then fine

2018-05-28 08:35 UTC, williamhogman commented
Great tests @bonahona

2018-05-28 08:36 UTC, williamhogman commented
Lets add @mantono too for review

2018-05-28 09:28 UTC, bonahona commented on src/main/kotlin/JobState.kt
> +        val lastInterceptor = WorkerInterceptor {
Not that I know of. This was the easiet way to put the execution of the desired worker function last.

2018-05-28 09:49 UTC, mantono requested changes
You cannot remove modifier `inline` on functions 
`require`, `execute`, `advanceIf`, `sideEffect`, `end`, `map` and `process`, since  now we cannot pass suspend functions to them, which is not acceptable.

2018-05-28 09:50 UTC, williamhogman commented
>You cannot remove modifier inline on functions
require, execute, advanceIf, sideEffect, end, map and process, since now we cannot pass suspend functions to them, which is not acceptable.

Perhaps `crossinline` is required  at some places

2018-05-28 09:50 UTC, mantono commented
```
    private suspend fun suspendingFunction() { "Lets do nothing" }

    @Test
    fun testMapWithSuspendFunctionWillCompile() {
        runBlocking {
            jobOne.map { suspendingFunction() }
        }
    }
```

This test case (if added) would not compile now

2018-05-28 09:58 UTC, mantono commented
@williamhogman Yes possibly, I am not sure what prompted the inline modifier to be removed in the first place, but I assume it was required in order for the interceptors to work?

2018-05-28 12:37 UTC, mantono commented
@bonahona @williamhogman `crossinline` did not work :( Added "test case" to check against.

2018-05-29 17:45 UTC, mantono commented on src/main/kotlin/JobState.kt
> +    suspend fun success(): JobState<U> = also { it.status = JobStatus.Success }
This one does not need the suspend modifier as it can never execute a suspending function.

2018-05-29 17:45 UTC, mantono commented on src/main/kotlin/JobState.kt
> +    fun end(predicate: (U) -> Boolean): JobStatus {
This one does need suspend however (you probably aware of that and just missed it) ;)

2018-05-29 17:45 UTC, mantono commented on src/main/kotlin/JobState.kt
> +    suspend fun end(): JobStatus {
suspend modifier is not needed here either.

2018-05-30 10:13 UTC, mantono requested changes
I use the following test cases to ensure that we can pass both suspend and non suspending functions to the function;
```
    private suspend fun suspendingFunction(): Boolean = true
    private fun nonSuspendingFunction(): Boolean = true

    @Test
    fun testMapWithSuspendFunctionWillCompile() {
        runBlocking {
            jobOne
                .advanceIf { suspendingFunction() }
                .execute { suspendingFunction() }
                .require { suspendingFunction() }
                .sideEffect { suspendingFunction() }
                .map { suspendingFunction() }
                .end { suspendingFunction() }
        }
    }

    @Test
    fun testMapWithNonSuspendFunctionWillCompile() {
        runBlocking {
            jobOne
                .advanceIf { nonSuspendingFunction() }
                .execute { nonSuspendingFunction() }
                .require { nonSuspendingFunction() }
                .sideEffect { nonSuspendingFunction() }
                .map { nonSuspendingFunction() }
                .end { nonSuspendingFunction() }
        }
    }
```

It they both pass, then I think we are all good.

2018-05-30 10:13 UTC, mantono commented on src/main/kotlin/JobState.kt
> +    suspend fun end(predicate: (U) -> Boolean): JobStatus {
We need a `suspend` on `predicate`.

2018-05-30 10:13 UTC, mantono commented on src/main/kotlin/JobState.kt
> +    suspend fun <R: Any> map(transform: (U) -> R): JobState<R> {
This function need to be changed to
```
    suspend fun <R: Any> map(transform: suspend (U) -> R): JobState<R> {
        val transFormedVal: R? = when (inProgress()) {
            true -> value?.let { transform(it) }
            false -> null
        }
```

2018-05-31 11:21 UTC, mantono approved these changes

2018-05-31 11:52 UTC, merged